[package]
name = "test_target"
version = "0.1.0"
authors = ["sum_catnip <catnip@catnip.fyi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
